apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemon-set
spec:
  template:
    metadata:
      labels:
        env: demo
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      env: demo

