apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-pod
  name: my-pod
spec:
  containers:
  - image: nginx
    name: my-pod
    resources: {}
    envFrom:
      - configMapRef:
          name: cm-one
      - secretRef:
          name: app-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

