apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depl
  labels:
    partOf: rs
    env: demo
spec:
  # inside template create complete pod template from your pod yaml
  template:
    metadata:
      name: nginx-pod
      labels:
        partOf: rs
    spec:
      containers:
      - name : nginx-container
        image: nginx
        ports:
        - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      partOf: rs
