apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-two
  name: nginx-two
spec:
  containers:
  - image: nginx
    name: nginx-two
    resources: {}
  dnsPolicy: ClusterFirst
  nodeSelector:
    gpu: "false"
  restartPolicy: Always
status: {}
