apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    env: demo
spec:
  containers:
  - name: my-app
    image: busybox:1.28
    command: ["sh", "-c", "echo the app is running && sleep 3600"]
    env:
    - name: API_KEY
      value: "1234"
  initContainers:
  - name: init-my-app
    image: busybox:1.28
    command: ["sh", "-c"]
    args: ["until nslookup my-app-svc.default.svc.cluster.local; do echo waiting for service to be up; sleep 3; done"]
